// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMJ97r9tuamvSHNCp8ryJyNG4ckofpSm0',
    appId: '1:436074388491:web:d84f7d0baf4a45ce7a7b0e',
    messagingSenderId: '436074388491',
    projectId: 'crypto-list-app-6d03d',
    authDomain: 'crypto-list-app-6d03d.firebaseapp.com',
    storageBucket: 'crypto-list-app-6d03d.appspot.com',
    measurementId: 'G-YH7JC00RDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKrtJP9u3k7Rz1mkn0i574C60V1NXMsI8',
    appId: '1:436074388491:android:f96b92f333436bc97a7b0e',
    messagingSenderId: '436074388491',
    projectId: 'crypto-list-app-6d03d',
    storageBucket: 'crypto-list-app-6d03d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGT3XovnbZVTksrzKiDC9_Ydo_wkPbx2s',
    appId: '1:436074388491:ios:81bdc32d6b2ba0787a7b0e',
    messagingSenderId: '436074388491',
    projectId: 'crypto-list-app-6d03d',
    storageBucket: 'crypto-list-app-6d03d.appspot.com',
    iosBundleId: 'com.alex.criptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGT3XovnbZVTksrzKiDC9_Ydo_wkPbx2s',
    appId: '1:436074388491:ios:81bdc32d6b2ba0787a7b0e',
    messagingSenderId: '436074388491',
    projectId: 'crypto-list-app-6d03d',
    storageBucket: 'crypto-list-app-6d03d.appspot.com',
    iosBundleId: 'com.alex.criptoCoinsList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMJ97r9tuamvSHNCp8ryJyNG4ckofpSm0',
    appId: '1:436074388491:web:70ed7613a198989c7a7b0e',
    messagingSenderId: '436074388491',
    projectId: 'crypto-list-app-6d03d',
    authDomain: 'crypto-list-app-6d03d.firebaseapp.com',
    storageBucket: 'crypto-list-app-6d03d.appspot.com',
    measurementId: 'G-GW72FL66J0',
  );
}
